#include <stdio.h>
#include <string.h>
int main()
{
	int num[102][102],n,i,j,x,y,t;
	while(scanf("%d",&n)&&n!=0)
	{
		for(i=0;i<=101;i++)
			for(j=0;j<=101;j++)
				num[i][j]=0;
		for(i=1;i<n;i++)
		{
			for(j=1;j<=n;j++)
			{
				scanf("%d%d",&x,&y);
				num[x][y]=i;
			}
			num[x][y]=i+n;
		}
		t=0;
		for(i=1;i<=n;i++)
		{
			for(j=1;j<=n;j++)
				if(num[i][j]==0)
				{
					if(t!=0)
						num[i][j]=n;
					else
					{
						t=1;
						num[i][j]=2*n;
					}
				}
		}
		if(n==1)
		{
			printf("good\n");
			continue;
		}
		t=0;
		while(t<n)
		{
			t++;
			for(i=1;i<n+1;i++)
				for(j=1;j<n+1;j++)
					if(num[i+1][j]==num[i][j]+n||num[i-1][j]==num[i][j]+n||num[i][j+1]==num[i][j]+n||num[i][j-1]==num[i][j]+n)
						num[i][j]+=n;
		}
		t=0;
		for(i=1;i<=n&&t==0;i++)
			for(j=1;j<=n&&t==0;j++)
				if(num[i][j]<=n)
					t=1;
		if(t==0)
			printf("good\n");
		else
			printf("wrong\n");
	}
	return 0;
}
