#include <iostream>
#include <math.h> 
#include <stdlib.h>
using namespace std;
int main()
{
	long num,n,i,w,j,k;
	char c=' ';
	while(cin>>n>>num&&!(n==0&&num==0))
	{
		if(n==0)
		{
			cout<<endl;
			continue;
		}
		if(num==1||num==0)
			w=1;
		else
			w=ceil(log10(num));
		for(i=w;i>0;i--)
		{
			if(i-w)
				cout<<c;
			cout<<c;
			if(num/(long)pow(10,(double)i-1)%10!=1&&num/(long)pow(10,(double)i-1)%10!=4)
				for(j=0;j<n;j++)
					cout<<'-';
			else
				for(j=0;j<n;j++)
					cout<<c;
			cout<<c;
		}
		cout<<endl;
		for(k=0;k<n;k++)
		{
			for(i=w;i>0;i--)
			{
				if(i-w)
					cout<<c;
				if(num/(long)pow(10,(double)i-1)%10==1||num/(long)pow(10,(double)i-1)%10==2||num/(long)pow(10,(double)i-1)%10==3||num/(long)pow(10,(double)i-1)%10==7)
				{
					for(j=0;j<=n;j++)
						cout<<c;
					cout<<"|";
				}
				else if(num/(long)pow(10,(double)i-1)%10==5||num/(long)pow(10,(double)i-1)%10==6)
				{
					cout<<"|";
					for(j=0;j<=n;j++)
						cout<<c;
				}
				else
				{
					cout<<"|";
					for(j=1;j<=n;j++)
						cout<<c;
					cout<<"|";
				}
			}
			cout<<endl;
		}
		for(i=w;i>0;i--)
		{
			if(i-w)
				cout<<c;
			cout<<c;
			if(num/(long)pow(10,(double)i-1)%10!=1&&num/(long)pow(10,(double)i-1)%10!=7&&num/(long)pow(10,(double)i-1)%10!=0)
				for(j=0;j<n;j++)
					cout<<'-';
			else
				for(j=0;j<n;j++)
					cout<<c;
			cout<<c;
		}
		cout<<endl;
		for(k=0;k<n;k++)
		{
			for(i=w;i>0;i--)
			{
				if(i-w)
					cout<<c;
				if(num/(long)pow(10,(double)i-1)%10==1||num/(long)pow(10,(double)i-1)%10==3||num/(long)pow(10,(double)i-1)%10==4||num/(long)pow(10,(double)i-1)%10==7||num/(long)pow(10,(double)i-1)%10==9||num/(long)pow(10,(double)i-1)%10==5)
				{
					for(j=0;j<=n;j++)
						cout<<c;
					cout<<"|";
				}
				else if(num/(long)pow(10,(double)i-1)%10==2)
				{
					cout<<"|";
					for(j=0;j<=n;j++)
						cout<<c;
				}
				else
				{
					cout<<"|";
					for(j=1;j<=n;j++)
						cout<<c;
					cout<<"|";
				}
			}
			cout<<endl;
		}
		for(i=w;i>0;i--)
		{
			if(i-w)
				cout<<c;
			cout<<c;
			if(num/(long)pow(10,(double)i-1)%10!=1&&num/(long)pow(10,(double)i-1)%10!=7&&num/(long)pow(10,(double)i-1)%10!=4)
				for(j=0;j<n;j++)
					cout<<"-";
			else
				for(j=0;j<n;j++)
					cout<<c;
			cout<<c;
		}
		cout<<endl<<endl;
	}
	return 0;
}
